general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'sbb-e1n9sandb'
      space: 'G1_General'
      credentialsId: '8a147d87-35b9-447f-9388-4f71ffdc0fa2'
